### ISSUE TITLE
QUESTION: Stop ParticlesView?

### ISSUE THREAD

**Issue by searchy2** [Doctoror/ParticlesDrawable#2]
Thanks for the amazing library! I am using it in conjunction with SlidingRootNav for some amazing effects: https://github.com/yarolegovich/SlidingRootNav/issues/10

There exists methods to stop Particles Drawable. However, no method exists for stopping ParticlesView. 
I have experimented a bit and discovered that if the view is hidden, CPU usage is greatly decreased. However, it appears that the particles are still being calculated? 

A quick hack I have found is to set the number of particles to 0 when the view is hidden so no particles are being calculated. Is that the best way to keep the particles from consuming resources?

**Comment by searchy2** [comment]
Update: setting the number of dots to 0 does not appear to stop the background calculations. Hmm, any ideas?

**Comment by Doctoror** [comment]
Thanks for opening this issue.

I was using `onAttachedToWindow()` and `onDetachedFromWindow()` callbacks to start and stop animations. There seems to be no other way for the View to know when to start or stop unless you explicitly tell it to.

In v1.0.1 I've added `start()` and `stop()` methods for the users of the View. You may use it to stop animations `onStop()` and start them in `onStart()`.

Also now it handles View visibility and will not start animating if View or one of it's parents are not visible, and will stop at the moment you set it as not visible.

I've deployed new release to maven central and it should be available any time soon as their severs sync.

Here's the full changelog for v1.0.1

ParticlesDrawable:
- Fixed IllegalArgumentException when set bounds resulted in width, height or both set to zero
- Added makeBrandNewFrame() method which resets all positions and makes a random new frame. Is useful if you are using ParticlesDrawable as static, not animating backgounrd.
- Added unit tests

ParticlesView:
- Now will not animate if visibility of this View or one of it's parents is not set to VISIBLE
- Added start() and stop() methods which allows you to control animations.
- Added unit tests

**Comment by searchy2** [comment]
@Doctoror Amazing! Thank you for making such a great library and sharing it! I can confirm that when the ParticleView is hidden, CPU usage and calculations stop. This greatly improves battery life. Thank you!
