### ISSUE TITLE
ParticleView Preview Error Since v1.0.5

### ISSUE THREAD

**Issue by searchy2** [Doctoror/ParticlesDrawable#3]
ParticleView had a really nice preview that displayed the generated particles in v1.0.4 and below. There are changes made in v1.0.5 that now cause an error in Android Studio preview. 
This is the stack trace of the error:

```
java.lang.VerifyError: Expecting a stackmap frame at branch target 20
Exception Details:
  Location:
    com/doctoror/particlesdrawable/ParticlesView.init(Landroid/content/Context;Landroid/util/AttributeSet;)V @5: if_icmplt
  Reason:
    Expected stackmap frame at this location.
```

Could the switch to SceneController from Particles Drawable in commit 5afb9214d96edacfcb4981260a99222b4457b8cc be the cause? 

The preview feature is not that important but it was nice to have the preview working and would be nice to have it back again. 

Preview v1.0.4 and below:
![particle view 1 4](https://user-images.githubusercontent.com/19896174/28603773-d6e9c87c-718b-11e7-9334-e07319ea78ae.png)

Preview v1.0.5 and above:
![particle view 1 7](https://user-images.githubusercontent.com/19896174/28603780-e01d19ee-718b-11e7-9a85-9dcfebd75461.png)

**Comment by Doctoror** [comment]
Thanks for reporting. I will take a look and fix it as soon as I can.
