### ISSUE TITLE
Failed to resolve: com.github.doctoror.particlesdrawable:library:2.0.0

### ISSUE THREAD

**Issue by hardcorelolo** [Doctoror/ParticlesDrawable#5]
Hey i updated to 2.0.0 but its saying

Failed to resolve: com.github.doctoror.particlesdrawable:library:2.0.0

Thanks

**Comment by Doctoror** [comment]
Hi. It's not yet on Maven. I will upload tomorrow. Thanks!

**Comment by Doctoror** [comment]
Sorry for the delay. It is now on Maven!
