### ISSUE TITLE
ERROR: Failed to resolve: library

### ISSUE THREAD

**Issue by skipper570** [Doctoror/ParticlesDrawable#7]
Hi,

I'm trying to use it with gradle:
`implementation 'com.github.doctoror.particlesdrawable:library:2.0.0'`

But I get the error "ERROR: Failed to resolve: library".
When I use 1.0.9 it works just fine.

**Comment by Doctoror** [comment]
I investigated and I see that the `aar` is not published. Seems that `gradle-mvn-push.gradle` does not see aars built with a module with `productFlavors`. I can't find a way around to this date. If you know a workaround for this (except using a single flavor) let me know.

**Comment by rausNT** [comment]
Unfortunately, I encountered the same problem. No solution yet?

**Comment by Doctoror** [comment]
I'm sorry @rausNT, I haven't seen your message on time.
I'm closing this as obsolete but feel free to reopen it if you still encounter this issue.
