### ISSUE TITLE
is there anyway to port this into jwjgl

### ISSUE THREAD

**Issue by ProfKambing** [Doctoror/ParticlesDrawable#9]
title.

**Comment by Doctoror** [comment]
I don't think there is any easy way, though you can try the following:
- take `library` package and port Android specific APIs to Java ones
- take `opengl` package and rewrite `renderer` implementation with your APIs to render meshes, you would have to remove the `chooser` packange and migrate `util` package to your APIs as well.

This is a pretty difficult task, you would probably waste at least a few days on it. Maybe it would be easier just to write a similar app your self from scratch.
